apiVersion: v1
kind: Namespace
metadata:
  name: parksmap-dev
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic-dev
spec:
  finalizers:
  - kubernetes