apiVersion: v1
kind: Namespace
metadata:
  name: parksmap-test
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic-test
spec:
  finalizers:
  - kubernetes